list(APPEND RESOURCES
        "public-pixel-font/PublicPixel-z84yD.ttf PublicPixelTTF"
        )

IF(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "OUTPUT_FILE variable must be defined")
ENDIF()

file(WRITE ${OUTPUT_FILE} "#include <span>\n")
file(WRITE ${HEADER_FILE} "#ifndef RESOURCES_H\n#define RESOURCES_H\n#include <span>\n")
file(APPEND ${HEADER_FILE} "// DO NOT EDIT - AUTOGENERATED FORWARD DECLARATION FOR EMBEDDED RESOURCES\n")

foreach(RESOURCE ${RESOURCES})
    string(REGEX MATCH "^([^ ]+)" filename ${RESOURCE})
    string(REGEX MATCH "([^ ]+)$" varname ${RESOURCE})
    message(STATUS "Generating variable ${varname} from file ${filename}")
    set(file "${CMAKE_CURRENT_SOURCE_DIR}/${filename}")
    file(READ ${file} filedata HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," filedata_formatted ${filedata})
    file(APPEND ${OUTPUT_FILE} "const static unsigned char ${varname}_ARRAY[] = {${filedata_formatted}};\n")
    # Declared extern "C" to make clang-tidy stop saying it's uninitialized
    file(APPEND ${OUTPUT_FILE} "extern \"C\" const std::span<const unsigned char> ${varname}(${varname}_ARRAY, ${varname}_ARRAY + sizeof(${varname}_ARRAY));\n")
    file(APPEND ${HEADER_FILE} "extern \"C\" const std::span<const unsigned char> ${varname};\n")
endforeach()

file(APPEND ${HEADER_FILE} "#endif\n")

